# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Create Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./react-app/
    env:
      CI: true
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: react-app/package-lock.json
    - run: npm i -g zcatalyst-cli
    - run: npm install 
      working-directory: ./react-app
    - name: Set CI environment variable to true
      run: export CI=true
    - run: catalyst deploy --project React3 --org 799162873 --token m_1004.a1e48fa83c972001406ac5ab703e9fbf.f6d699a427bf9b1f954e72382fbfa519
    
